
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_40
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_38
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_48

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_21
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_47
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO GPIO_NUM_17
#define BOOT_BUTTON_GPIO GPIO_NUM_1

#define RESET_NVS_BUTTON_GPIO GPIO_NUM_NC
#define RESET_FACTORY_BUTTON_GPIO GPIO_NUM_NC

#define BATTERY_ADC_PIN GPIO_NUM_3

// QMI8658 6DOF IMU sensor pins (dedicated I2C bus)
#define QMI8658_I2C_SDA_PIN GPIO_NUM_11
#define QMI8658_I2C_SCL_PIN GPIO_NUM_12

// Gesture mouse button detection via ADC
#define GESTURE_BUTTON_ADC_PIN GPIO_NUM_9  // ADC1_CH8

// #define ML307_RX_PIN GPIO_NUM_12
// #define ML307_TX_PIN GPIO_NUM_13

#endif // _BOARD_CONFIG_H_
